version: '3.5'

services:
  cardEncryptor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'card_encryptor'
    restart: always
    ports:
      - 3001:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm start"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14
    container_name: card_encryptor_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  default:
    name: local
