apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-card-encryptor-deployment
spec:
  selector:
    matchLabels:
      app: api-card-encryptor
  template:
    metadata:
      labels:
        app: api-card-encryptor
    spec:
      containers:
        - name: api-card-encryptor-deployment
          image: devrsilva/card-encryptor-microservice
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/livenessProbe
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/readinessProbe
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: database-url
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: postgres-host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: postgres-password
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: api-card-encryptor-secrets
                  key: port
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-card-encryptor-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: api-card-encryptor-secrets
type: Opaque
stringData:
  postgres-db: card-encryptor
  postgres-user: postgres
  postgres-password: postgres
  postgres-host: card-encryptor.czg2ea2yu0rz.us-east-1.rds.amazonaws.com
  database-url: postgresql://postgres:postgres@card-encryptor.czg2ea2yu0rz.us-east-1.rds.amazonaws.com:5432/registration?schema=public
  port: '3002'
---
apiVersion: v1
kind: Service
metadata:
  name: api-card-encryptor-svc
spec:
  selector:
    app: api-card-encryptor
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30008
  type: LoadBalancer
